project:
  type: website
  output-dir: docs

website:
  title: "younghowebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - bio.qmd
      - project.qmd
      - text: CV
        url: /CV.pdf
      - text: Resume
        url: /resume.pdf


format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

